### ISSUE TITLE
Unsigned Plugin / Workaround

### ISSUE THREAD

**Issue by nmaas87** [yamcs/grafana-yamcs#10]
FYI: Since Grafana 8.x it does restrict loading of unsigned plugins.
To allow Grafana to load the grafana-yamcs plugin, you need to change

````
;allow_loading_unsigned_plugins = 
````

to

````
allow_loading_unsigned_plugins = yamcs-yamcs-datasource
````

within the grafana.ini

See: https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins

**Comment by nmaas87** [comment]
Addition, if you want to setup grafana-yamcs on an internet connected Debian 10 machine with Docker installed and just want a quick and dirty setup (not production hardend!):

````
# become root
su -
cd /root
# create folder for grafana data
mkdir grafana
# delete old grafana instances, e.g. for update
docker rm grafana --force
# extract grafana.ini into /root/
docker cp $(docker create --rm grafana/grafana:8.0.3):/etc/grafana/grafana.ini ./grafana.ini
# set the override for unsigned plugins for yamcs
sed -i 's/;allow_loading_unsigned_plugins.*/allow_loading_unsigned_plugins = yamcs-yamcs-datasource/' grafana.ini
# get the user ID to run in the right context
ID=$(id -u)
# run grafana and install yamcs plugin
docker run -d -p 3000:3000 \
    --name grafana \
    --user $ID \
    -v "$PWD/grafana:/var/lib/grafana" \
    -v "$PWD/grafana.ini:/etc/grafana/grafana.ini" \
    -e "GF_INSTALL_PLUGINS=https://github.com/yamcs/grafana-yamcs/releases/download/v2.1.0/yamcs-yamcs-datasource-2.1.0.zip;yamcs-yamcs-datasource" \
    --restart=always \
    grafana/grafana:8.0.3
````
* ogin with admin:admin on IP:3000
* create new user password
* add Yamcs datasource with correct URL and instance, then click Save & Test
* enjoy :)

**Comment by fqqb** [comment]
Thanks. Added to README, and fixed dev setup.

(I'll go through their signing process some time soon)
