### ISSUE TITLE
Queries do not complete

### ISSUE THREAD

**Issue by keck-in-space** [yamcs/grafana-yamcs#3]
Hello,

We have a yamcs instance running on the same server as our grafana instance. We've added the data source and can properly browse the data names for our instance, but no queries ever resolve to have data. They just run forever and never produce any data members. Is there something I'm missing?

For reference, I do get an error in the web browser console when making queries that I can't establish a connection to ws://localhost:8090/api/websocket.

I'm also accessing the Grafana instance from a browser that is not on the local server. Is that a requirement currently?

Looking at this line

https://github.com/yamcs/grafana-yamcs/blob/eccdec9383ceb667480a54fe42c21c01d6888eaa/src/DataSource.ts#L39

I'm really not sure if that means that it will always access the localhost of the client accessing the Grafana instance. If so, it seems like it could be updated to use the URL given in the datasource configuration.

Thank you!

**Comment by Flilzkov** [comment]
Hello,

The current version is a work in progress, with intent to add support for realtime telemetry. This part does not currently support authentication, it has so far been tested without the yamcs authentication modules. This is probably the cause of your issue (the data names are fetched using authentication, but data queries are not). You are as well right for pointing out the hardcoded server address, this indeed makes plugin access the local server only.

The stable version can be found in the release section [here](https://github.com/yamcs/grafana-yamcs/releases/tag/v1.0.0). In that version, the data is queried manually or using the auto-refresh option.

**Comment by keck-in-space** [comment]
Thanks for the help. Just so I'm understanding you -- are you saying that I should make a user that requires no password and use that for the configuration for now?

Also, I'm not sure I'm fully following the implications of the hardcoded server address. Does that mean only browsers that are running on the server itself can be used to access the Yamcs data with Grafana? If so, could I edit the localhost address in the code to point to my server and rebuild the plugin (under the assumption that all accessing the server also have access to the Yamcs instance)?

I'll also try building the stable version you've referenced.

One last thing if it helps: we're running Yamcs 4.10.9.

Thanks!

**Comment by keck-in-space** [comment]
I was just able to try the stable version and it works! Thanks for the help. Would we want to edit the README to refer to the stable version instead of pulling that latest? That's where we had issues.

**Comment by Flilzkov** [comment]
Thank you for your feedback ! 
Yes, the README should be updated.

**Comment by Flilzkov** [comment]
Concerning the version in development : 
> Thanks for the help. Just so I'm understanding you -- are you saying that I should make a user that requires no password and use that for the configuration for now?
> 
The user and password are not used in the websocket connection, so I do not believe that creating a user without password would work. This was tested using a Yamcs server without authentication module (the stable version works with user authentication).

> Also, I'm not sure I'm fully following the implications of the hardcoded server address. Does that mean only browsers that are running on the server itself can be used to access the Yamcs data with Grafana? If so, could I edit the localhost address in the code to point to my server and rebuild the plugin (under the assumption that all accessing the server also have access to the Yamcs instance)?

You are right on the implication of the hardcoded server address, and editing it with your server address before rebuilding the plugin should work. Note that you would also need to replace the instance name here as well :
https://github.com/yamcs/grafana-yamcs/blob/eccdec9383ceb667480a54fe42c21c01d6888eaa/src/DataSource.ts#L78-L86

**Comment by keck-in-space** [comment]
Thank you! This is very helpful.

**Comment by fqqb** [comment]
The master branch has been updated to remove partially developed features:

- No websocket (for now) (still available on websocket branch for a later revisit)
- No authentication (for now) (it was triggering continuous 401 requests on non-secured servers)

With these changes the localhost hardcoding is gone, as well as the username/password options. I believe that closes the current issue.

Btw, I'm noticing that port '8090' and scheme 'http://' are also hardcoded, but I will revisit that for a next release. Probably will introduce just a "Server URL" option.
