### ISSUE TITLE
Version requirement

### ISSUE THREAD

**Issue by keck-in-space** [yamcs/grafana-yamcs#4]
What is the minimum version of the yamcs server required to use this plug in?

Thank you

**Comment by Flilzkov** [comment]
The plugin has been tested on the versions > 5.2.0.

**Comment by keck-in-space** [comment]
Thank you. We are running 4.10.9. I'm not sure if this will work for our instance, but will report back if I can get it working.

**Comment by keck-in-space** [comment]
The stable version works on 4.10.9 for our instance. It might be nice to somehow put this in the documentation, but I don't know how we'd know the compatibility without testing all the older versions of Yamcs.

**Comment by fqqb** [comment]
Closing as we have no plans to test against legacy versions of Yamcs. As a general rule, community support assumes that you use recent versions (Yamcs 5 has been out for a while already).
