### ISSUE TITLE
Support for 'member' parameters

### ISSUE THREAD

**Issue by h-roon** [yamcs/grafana-yamcs#7]
Currently the query tool does not allow you to get to the ‘member’ class past parameters. Sometimes these member parameters can also have further member/aggregate parameters. Maybe some logic should be built to all the query tool to get to the bottom-most layer?

**Comment by h-roon** [comment]
Currently the query tool does not allow you to get to the ‘member’ class past parameters. Sometimes these member parameters can also have further member/aggregate parameters. Maybe some logic should be built to all the query tool to get to the bottom-most layer?

**Comment by fqqb** [comment]
On master (and released as of v2.1.0)

With the help of some new server API (use v5.5.x) autocomplete can now expand aggregate (or nested aggregate) members based on a partial search string, and present them in the list of suggestions. The expansion stops at where it reaches an array member. Only when you enter a specific array index, it can expand further down.
