### ISSUE TITLE
Query type results in data averaging

### ISSUE THREAD

**Issue by keck-in-space** [yamcs/grafana-yamcs#8]
Hello,

While using this plugin we have noticed that some of the data values that are being plotted are really averages of two (or more) data points that occur close together in time.

I believe this plug-in is using [Get Parameter Samples](https://docs.yamcs.org/yamcs-http-api/parameter-archive/get-parameter-samples/) which states

> This divides the query interval in a number of intervals and returns aggregated statistics (max,min,avg) about each interval. This operation is useful when making high-level overviews (such as plots) of a parameter’s value over large time intervals without having to retrieve each and every individual parameter value.

Is there any way to make another query type that does not average the incoming data and thus does not display data values in Grafana that are not actually in the Yamcs mission database?

Thank you!

**Comment by fqqb** [comment]
I think this is compatible with most other Grafana datasource plugins. Sampling prevents transferring large quantities of data from Yamcs to Grafana. For example, if you look at a 1 year plot of a 1 Hz parameter, it would be really wasteful (and slow) to query for all individual values.

I would agree that for newly incoming values we could do a better job, for example by using the 'Streaming' option of Grafana. Then the incoming values would be appended to the older (sampled) values. This subject is yet to be explored.

**Comment by keck-in-space** [comment]
Thanks for the reply. We can somewhat work around this for now by increasing the Max Data Points filed in the query options; it is an imprecise solution, however. We just increase it to some arbitrarily large number and hope that averaging doesn't occur. 

I understand why it happens, but the graphs showing values that aren't actually in the database has confused some people since we never expect those values to occur. I suppose we can use another tool for now, or look into modifying this plugin to use List Parameter History instead. https://docs.yamcs.org/yamcs-http-api/parameter-archive/list-parameter-history/

**Comment by fqqb** [comment]
i'm working on an update where you will also have the option to have series for min/max in addition to avg.
I also plan to add list-parameter-history (and get-parameter-value), but list-parameter-history will only do 1 page.

I think sampling plots is the only correct way, and is what happens on yamcs-web too. If you have 10 parameters for 1 pixel, you average the value server-side and avoid the data transfer, your user screen pixel density wouldn't be able to accurately show anyway.

**Comment by xpromache** [comment]
You get also the min/max which are actual values. I guess you can have an option to display those instead of the average. 
Note that yamcs-web in fact displays all three, like you can see in the screenshot below (the dark blue is the average and the light blue is min/max).
 

![image](https://user-images.githubusercontent.com/909383/112002618-5ff46a80-8b20-11eb-8e05-f85f4fc4c1be.png)

**Comment by xpromache** [comment]
> Thanks for the reply. We can somewhat work around this for now by increasing the Max Data Points filed in the query options; it is an imprecise solution, however. We just increase it to some arbitrarily large number and hope that averaging doesn't occur.
> 
> I understand why it happens, but the graphs showing values that aren't actually in the database has confused some people since we never expect those values to occur. I suppose we can use another tool for now, or look into modifying this plugin to use List Parameter History instead. https://docs.yamcs.org/yamcs-http-api/parameter-archive/list-parameter-history/

Could it be that you are not trying to plot analog values? A sensor (measuring a temperature for example) will be limited in accuracy anyway so the very exact value doesn't mean too much (there is always some noise). 

If you want to display other values like enumerations which have a limited set of values, that is not the right query, this one is more appropriate:
https://docs.yamcs.org/yamcs-http-api/parameter-archive/get-parameter-ranges/

Some Grafana support for that will be added also at some point.

**Comment by keck-in-space** [comment]
That's interesting. Showing either the min or the max for a given time point would be fine for our use case. I agree that requesting all the data and then being unable to show it due to limitations in the display is the wrong approach. I just also think showing values that don't exist in the database can be confusing for some users, especially when they never expect to see values in that range.

We have a channel that only has values around 0-0.05 or 220-270. When it transitions between those two values, there are averages that are around 120 which have confused those reading the graphs since those values should not be occurring in normal operation.

This isn't an enumeration channel. It's a true sensor reading. Though Get Parameter Ranges might be an acceptable solution. I think mainly the users don't want values that don't exist in the database to show in the view. If we have to discard some values in-between that is an acceptable compromise.

**Comment by xpromache** [comment]
The get parameter ranges is meant for enumerations; it should work for the analog values but provide the most common n values if that is of any use.

I think for your use case we should have a get samples which is somehow aware of the two intervals and never averages between them but only inside. Then the result will hopefully make sense. 

We should remember this use case for future improvements... for now the option for showing the min/max currently being implemented by Fabian is the best we have.

**Comment by keck-in-space** [comment]
Thanks so much for the reply. I agree what you're describing sounds like a good approach -- average the values when they differ only a little, but stop averaging should they differ by a certain threshold, perhaps.

I'll look forward to the min/max implementation as a possible solution, and depend on increasing Max Data Points for the affected views for now.

**Comment by fqqb** [comment]
Should be addressed in v2.0.0:
* Added min/max/count (in addition to avg) for sampling queries.
* Added a 'Get Parameter Value History' query type, which does not process the data, but returns only the most recent 500 points.

Let us know if you encounter bugs in the implementation.

**Comment by keck-in-space** [comment]
Wow! That was fast. Thank you for the update!
